#!/bin/bash

# Path to script that will be executed before starts docker-compose
ENV_SCRIPT="./create-env.sh"

# Check script
if [ -x "$ENV_SCRIPT" ]; then
    echo "executing $ENV_SCRIPT..."
    $ENV_SCRIPT
else
    echo "Error: $ENV_SCRIPT not found or not executable."
    exit 1
fi

# Execute docker-compose with all parameters an sub commannds
docker-compose "$@"
